# Change these first
owner: acumenlabs # Your GitHub username
repo: status-page # Your Github repository name

# Add your sites here
sites:
  - name: Acumen Website
    url: https://www.acumen.io
  - name: Acumen API
    url: $BACKEND_URL
  - name: Fetchers
    url: $STATUS_URL
    method: POST
    body: '{"username": "$GH_USERNAME", "password": "$GH_SECRET", "statusType": "fetchers"}'
    __dangerous__body_down: "more than 30% of fetchers are down"
    __dangerous__body_degraded: "between 0-30% of fetchers are down"
  - name: Processors
    url: $STATUS_URL
    method: POST
    body: '{"username": "$GH_USERNAME", "password": "$GH_SECRET", "statusType": "processors"}'
    __dangerous__body_down: "more than 30% of data processors are down"
    __dangerous__body_degraded: "between 0-30% of data processors are down"

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.acumen.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /status-page
  logoUrl: https://app.acumen.io/assets/images/logo-dark.svg
  name: Acumen Status Page
  introTitle: "Acumen Labs status monitor page"
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: Acumen.io
      href: https://www.acumen.io
workflowSchedule:
  graphs: "*/15 * * * *"
  responseTime: "*/15 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"