# Change these first
owner: acumenlabs # Your GitHub username
repo: status-page # Your Github repository name

# Add your sites here
sites:
  - name: Acumen Website
    url: https://www.acumen.io
  - name: Acumen API
    url: $BACKEND_URL

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: http://status.acumen.io/
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /status-page
  logoUrl: https://app.acumen.io/assets/images/logo-dark.svg
  name: Acumen Status Page
  introTitle: "Acumen Labs status monitor page"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Acumen.io
      href: https://www.acumen.io

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
